### PR TITLE
Enhancing the nsstring check and using a length check

### PR DESCRIPTION
**Pull request by jdizoglio**

### CODE REVIEW

**Comment by boxcla** [comment]
Verified that @jdizoglio has signed the CLA. Thanks for the pull request!

**Comment by jdizoglio** [comment]
@RicoYao

**Comment by boxtcarpel** [comment]
> 0 might be more intuitive ;)

+2 LGTM

:flower_playing_cards:

**Comment by boxtcarpel** [comment]
That's supposed to be "greater than 0"

**Pull request merged**
