### PR TITLE
IOS-15890 Video conversion in progress should check 'viewable' status…

### PR DESCRIPTION
**Pull request by jdizoglio**
… as well as 'success' for reps status

### CODE REVIEW

**Comment by boxcla** [comment]
Verified that @jdizoglio has signed the CLA. Thanks for the pull request!

**Review by Prithvijutur — APPROVED** [review]
lgmt

**Comment by Prithvijutur** [comment]
Nit: Would be nice to have a comment against viewable status since the name isn't descriptive enough by itself

**Comment by jdizoglio** [comment]
retry

**Pull request merged**
