### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by JonathanHoffman**
The README did not display a couple of links correctly. Merging this pull request will fix two links to the Carthage repo.

This is a really small change, but if there are any steps from the [contributing guidelines](https://github.com/box/box-ios-sdk/blob/master/CONTRIBUTING.md) I need to fill out before merging (e.g. opening an issue), please let me know.

### CODE REVIEW

**Comment by boxcla** [comment]
Hi @JonathanHoffman, thanks for the pull request. Before we can merge it, we need you to sign our Contributor License Agreement. You can do so electronically here: http://opensource.box.com/cla

Once you have signed, just add a comment to this pull request saying, "CLA signed". Thanks!

**Comment by JonathanHoffman** [comment]
CLA signed

**Comment by boxcla** [comment]
Verified that @JonathanHoffman has just signed the CLA. Thanks, and we look forward to your contribution.

**Comment by JonathanHoffman** [comment]
It looks like merging #479 would fix the failing travis check. :)

**Review by Prithvijutur — APPROVED** [review]
Approved. Thanks for contributing!

**Pull request closed without merging**
