### PR TITLE
Treat `null` as `nil` for defaultInviteeRole

### PR DESCRIPTION
**Pull request by jlawton**

### CODE REVIEW

**Comment by boxcla** [comment]
Verified that @jlawton has signed the CLA. Thanks for the pull request!

**Review by Prithvijutur — APPROVED** [review]
+1

**Review by boxtcarpel — APPROVED** [review]

**Comment by potrebic** [comment]
Add the JIRA to the bug title.

**Comment by jlawton** [comment]
The ticket is actually there in the commit. We generally don't do that for PRs in public SDKs, historically.

**Pull request merged**
