### PR TITLE
Update for iPhone SE and 9.7-inch iPad Pro

### PR DESCRIPTION
**Pull request by stevemoser**

### CODE REVIEW

**Comment by boxcla** [comment]
Hi @stevemoser, thanks for the pull request. Before we can merge it, we need you to sign our Contributor License Agreement. You can do so electronically here: http://opensource.box.com/cla

Once you have signed, just add a comment to this pull request saying, "CLA signed". Thanks!

**Comment by stevemoser** [comment]
CLA signed

**Comment by boxcla** [comment]
Verified that @stevemoser has just signed the CLA. Thanks, and we look forward to your contribution.

**Comment by boxtcarpel** [comment]
+2 LGTM (values match http://www.iphonetopics.com/download-ios-9-3-for-iphone-ipad-ipod-touch-ipsw-links/)

:bow:

**Pull request merged**
