### PR TITLE
Converting methods used to set keychain prefix & access group to be

### PR DESCRIPTION
**Pull request by sowmiya**
class methods

### CODE REVIEW

**Comment by boxcla** [comment]
Verified that @sowmiya has signed the CLA. Thanks for the pull request!

**Comment by sowmiya** [comment]
Since there is more than one way to create a contentClient, it is tedious to set up the keychain prefix and access groups for each instance. Also, the prefix & access group strings are static already.

**Comment by boxtcarpel** [comment]
+2 LGTM

:golf:

**Comment by RicoYao** [comment]
Good change. It's a breaking change, but hopefully no-one was using those methods yet. Let's go for it.

**Pull request merged**
