### PR TITLE
fixed documentation typos.

### PR DESCRIPTION
**Pull request by bazik123**
this change fixes little typos in documentation files' snippets and comments.

### CODE REVIEW

**Comment by boxcla** [comment]
Hi @bazik123, thanks for the pull request. Before we can merge it, we need you to sign our Contributor License Agreement. You can do so electronically here: http://opensource.box.com/cla

Once you have signed, just add a comment to this pull request saying, "CLA signed". Thanks!

**Comment by bazik123** [comment]
CLA signed

**Comment by boxcla** [comment]
Verified that @bazik123 has just signed the CLA. Thanks, and we look forward to your contribution.

**Comment by bazik123** [comment]
apparently not needed, closing.

**Review by boxtcarpel — APPROVED** [review]

**Comment by boxtcarpel** [comment]
Thanks @bazik123 for the cleanup! Sorry we missed this earlier.

**Pull request merged**
