### PR TITLE
Use NS_ENUM to make sure bridging to Swift is correct

### PR DESCRIPTION
**Pull request by piercifani**
Addresses https://github.com/box/box-ios-sdk/issues/310

### CODE REVIEW

**Comment by boxcla** [comment]
Hi @piercifani, thanks for the pull request. Before we can merge it, we need you to sign our Contributor License Agreement. You can do so electronically here: http://opensource.box.com/cla

Once you have signed, just add a comment to this pull request saying, "CLA signed". Thanks!

**Comment by piercifani** [comment]
CLA signed

**Comment by boxcla** [comment]
Verified that @piercifani has just signed the CLA. Thanks, and we look forward to your contribution.

**Review by boxtcarpel — APPROVED** [review]

**Comment by boxtcarpel** [comment]
Thanks, @piercifani ! That's a great catch, sorry we missed it. This change is also valuable for 64-bit compatibility.

**Pull request merged**
