### PR TITLE
Update the stream operation to use NSURLSession instead of NSURLConnection

### PR DESCRIPTION
**Pull request by boxtcarpel**

### CODE REVIEW

**Comment by boxcla** [comment]
Verified that @boxtcarpel has signed the CLA. Thanks for the pull request!

**Comment by boxtcarpel** [comment]
FYI @jdizoglio

**Comment by thuyBox** [comment]
LGTM 👍

**Comment by jdizoglio** [comment]
reviewed for AVLoaderDelegate, looks good.

**Pull request merged**
