### PR TITLE
migrating the 3.8.x representations commit to primary dev

### PR DESCRIPTION
**Pull request by jdizoglio**
Cherry picking original representations code. Wired-off the file parsing and tests code where needed.

### CODE REVIEW

**Comment by boxcla** [comment]
Verified that @jdizoglio has signed the CLA. Thanks for the pull request!

**Comment by thuyBox** [comment]
it looks safe to me, looks like no request is using stream operation yet. +2

**Comment by boxtcarpel** [comment]
Should we close #250 ?

**Comment by jdizoglio** [comment]
@boxtcarpel will do

**Pull request merged**
