### PR TITLE
Fix clearing of tokenInfo

### PR DESCRIPTION
**Pull request by smowris**
### Issue Link :link:

The revoked token was not properly clearing causing a 401 error. This fix clears the revoked token so the new token can be saved.

### CODE REVIEW

**Comment by jlawton** [comment]
The root cause of this bug was the decision to have 2 sources of truth about the token in `DelegatedAuthSession`. There is both a `tokenStore` and a `tokenInfo`. Given that decision, this looks like a good change to me. We don't want revoked tokens hanging around.

Independent of the fix here (which I think we should take), it might be worth re-visiting the initial decision. Are token store reads expected to be too expensive?

**Review by PJSimon — DISMISSED** [review]

**Comment by PJSimon** [comment]
@smowris Looks good!  Can you sign the CLA so I can merge this?  Thanks!

**Comment by jlawton** [comment]
@PJSimon CLA is signed.

**Review by PJSimon — DISMISSED** [review]

**Comment by PJSimon** [comment]
@smowris It looks like this bug exists in other auth classes, too:
- https://github.com/box/box-ios-sdk/blob/master/Sources/Sessions/OAuth2/OAuth2Session.swift#L121
- https://github.com/box/box-ios-sdk/blob/master/Sources/Sessions/SingleToken/SingleTokenSession.swift#L26
Are you in a good position to use the same method you used to find this bug to test that it also exists using the other authentication methods?

**Comment by smowris** [comment]
@PJSimon The other sessions don't support setting tokenInfo to nil. So it isn't necessary to change those other files

**Review by PJSimon — APPROVED** [review]

**Pull request merged**
