### PR TITLE
switch UIWebView to WKWebView.

### PR DESCRIPTION
**Pull request by OneSecure**
Hi @PJSimon, 
I need your help. 
When I upload my App to AppStore, Apple staff email me that they will forbid UIWebView in the future. So I have to change the code. but BOX server tell me that something went wrong.
can you help me to complete the migrating?

And this issue is mentioned in #669 and #647, and I don't like `Swift`.

### CODE REVIEW

**Comment by OneSecure** [comment]
Hi @PJSimon, 
I have finished the work, now I have test `OAuth Accounts` successfully. 
But I have no condition test it with `AppUser Accounts`, It's need your help.
I have removed `NSURLSessionDataDelegate` protocol and it's code, but I do not delete the tons of code, just comment it out. You can review it.

I have tested it successfully on `iOS 12` and `iOS 9` and `iOS 13 simulator`.

Hope you can merge it into `objective-c-maintenance` branch.

**Comment by PJSimon** [comment]
@OneSecure I'll take a look soon! Thanks!

**Comment by redbug26** [comment]
Could you do the merge ? 
Thanks ;)

**Comment by PJSimon** [comment]
@OneSecure @redbug26 Sorry for the delay - we'll do the code review this week! (SDK-1357)

**Comment by dev-meanlabs** [comment]
This is now blocking new app submissions. Please have it reviewed and merged asap. Thanks :-)

**Comment by jlawton** [comment]
@OneSecure would you try running off the https://github.com/box/box-ios-sdk/tree/wkwebview-auth branch? I think it might be a cleaner change if it works for you.

**Comment by OneSecure** [comment]
@jlawton I have tested it #715. It looks work fine.

**Comment by PJSimon** [comment]
@OneSecure is looks like everything in this PR is covered in #715, so I'm going to close this PR.  Please re-open and message me if that's not correct.

**Pull request closed without merging**
