### PR TITLE
update .podspec, remove -ObjC and -all_load flags

### PR DESCRIPTION
**Pull request by aletan**
Fix conflict with other pods (example libjingle_peerconnection)

### CODE REVIEW

**Comment by boxcla** [comment]
Hi @aletan, thanks for the pull request. Before we can merge it, we need you to sign our Contributor License Agreement. You can do so electronically here: http://opensource.box.com/cla

Once you have signed, just add a comment to this pull request saying, "CLA signed". Thanks!

**Comment by aletan** [comment]
CLA signed

**Comment by boxcla** [comment]
Verified that @aletan has just signed the CLA. Thanks, and we look forward to your contribution.

**Comment by RicoYao** [comment]
@aletan Thanks for submitting this.

I believe the reason we added all_load was to have the categories compiled in. Without it, one might run into runtime errors (crashes). We should test that category methods still work with this, and also look into whether we need to use force_load instead of all_load.

**Comment by boxtcarpel** [comment]
We have moved to using Carthage. Thank you for your pull request and for using the SDK.

**Pull request closed without merging**
