### PR TITLE
Update the readme documentation to include app setup instructions

### PR DESCRIPTION
**Pull request by boxtcarpel**
Added some helpful information about configuring one's application
on developers.box.com, especially around the settings required for
authentication to work.

### CODE REVIEW

**Comment by boxcla** [comment]
Hi @boxtcarpel, thanks for the pull request. Before we can merge it, we need you to sign our Contributor License Agreement. You can do so electronically here: http://opensource.box.com/cla

Once you have signed, just add a comment to this pull request saying, "CLA signed". Thanks!

**Comment by boxtcarpel** [comment]
CLA signed

**Comment by boxcla** [comment]
Verified that @boxtcarpel has just signed the CLA. Thanks, and we look forward to your contribution.

**Comment by boxtcarpel** [comment]
https://github.com/box/box-ios-content-sdk/issues/13

**Comment by RicoYao** [comment]
LGTM

**Pull request merged**
