### PR TITLE
Add requestAllCommentsFields to BOXCommentAddRequest

### PR DESCRIPTION
**Pull request by h2kuo**

### CODE REVIEW

**Comment by boxcla** [comment]
Verified that @h2kuo has signed the CLA. Thanks for the pull request!

**Comment by boxtcarpel** [comment]
+2 LGTM

:alarm_clock:

**Comment by h2kuo** [comment]
@scottliubox

**Comment by RicoYao** [comment]
+2

**Comment by scottliubox** [comment]
+2

**Pull request merged**
