### PR TITLE
Update sample app to be compatible with CocoaPods 1.0.0

### PR DESCRIPTION
**Pull request by h2kuo**
Also fixed project to remove CocoaPods warnings.

### CODE REVIEW

**Comment by boxcla** [comment]
Verified that @h2kuo has signed the CLA. Thanks for the pull request!

**Comment by h2kuo** [comment]
For issue #226

**Comment by boxtcarpel** [comment]
+2 LGTM

🍶

**Comment by boxtcarpel** [comment]
+2 LGTM

much better!

🐻

**Pull request merged**
