### PR TITLE
Fix EXC_BAD_ACCESS crash in BOXAPIDataOperation caused by removing th…

### PR DESCRIPTION
**Pull request by jpang1**
…e outputStream from runLoop and then closing.

### CODE REVIEW

**Comment by boxcla** [comment]
Hi @jpang1, thanks for the pull request. Before we can merge it, we need you to sign our Contributor License Agreement. You can do so electronically here: http://opensource.box.com/cla

Once you have signed, just add a comment to this pull request saying, "CLA signed". Thanks!

**Comment by jpang1** [comment]
CLA signed

**Comment by boxcla** [comment]
Verified that @jpang1 has just signed the CLA. Thanks, and we look forward to your contribution.

**Comment by boxtcarpel** [comment]
+2 LGTM

Closing a stream removes it from any scheduled runloop.

:clapper:

**Comment by RicoYao** [comment]
+2 I never did understand why that was in there in the first place.

**Pull request merged**
